# netlify.toml

[build]
  publish = "."    # Publica a raiz (onde está index.html)
  command = ""     # Sem build step

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = { "Basic-Auth" = ":senha123" }
