# netlify.toml

[build]
  publish = "."       # publica a raiz (onde index.html está)
  command = ""        # sem build step (site estático)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = { "Basic-Auth" = ":senha123" }
