# netlify.toml

[build]
  publish = "."      # pasta onde está index.html
  command = ""       # sem build step

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { Role = [] }     # (em vaga de roles podemos usar Basic Auth abaixo)
  # Basic Auth:
  force = true
  headers = { "Basic-Auth" = ":senha123" }
